### ISSUE TITLE
Proxy mode no longer working?

### ISSUE THREAD

**Issue by JDanabar** [KudoAI/googlegpt#11]
Hello,

Proxy mode no longer works for me. It does work when I sign into chat.openai.com and then do a google search, but I much prefer the privacy of not having to sign-in. 

Gets hung on "Waiting for ChatGPT reponse..."

![image](https://github.com/KudoAI/googlegpt/assets/60204329/c34976d9-b2f7-46a5-9fe5-7654656f26b7)

**Comment by adamlui** [comment]
Hey @JDanabar the aigcfun.com proxy API I was using stopped working, I will get on fixing this immediately (I've been severely stricken with COVID so did not have enough time to work on it, sorry)

**Comment by Cozy888** [comment]
Is there any update for this ?

**Comment by wizpizz** [comment]
The script literally doesn't work because this isn't fixed

**Comment by matterhub** [comment]
Script still broken. Doesn't matter if signed on to ChatGPT and/or Google. It never gets past "Waiting for ChatGPT response."
It's been broken for quite a while so there might not be a solution to this. Might be time to move on to Bing + Copilot. I couldn't care much for Bing but Copilot provides accurate answers without having to check several search results.

**Comment by adamlui** [comment]
@JDanabar @Cozy888 @wizpizz @matterhub sorry for the delay but I added new endpoints/routines so Proxy Mode will work now
