### ISSUE TITLE
Opera GX

### ISSUE THREAD

**Issue by ozilwg** [KudoAI/googlegpt#14]
Nothing is displayed on the Opera GX browser

**Comment by adamlui** [comment]
hey @ozilwg i'm downloading it now to test, what userscript manager are you using?

**Comment by adamlui** [comment]
@ozilwg after extensive research, I found Opera GX blocks latest Tampermonkey as malicious

https://www.reddit.com/r/OperaGX/comments/19bvkbt/opera_gx_fullon_disabled_one_of_my_extensions/?rdt=61722
https://forums.opera.com/topic/30359/tampermonkey-chrome-extension-blocked/26?lang=en-US

The last working version is 4.18ish which is far from 5.0 so many userscripts don't work, also I tested Violentmonkey similarly fails, so my only recommended solution is using a better browser

**Comment by adamlui** [comment]
> > @ozilwg after extensive research, I found Opera GX blocks latest Tampermonkey as malicious
> > https://www.reddit.com/r/OperaGX/comments/19bvkbt/opera_gx_fullon_disabled_one_of_my_extensions/?rdt=61722 https://forums.opera.com/topic/30359/tampermonkey-chrome-extension-blocked/26?lang=en-US
> > The last working version is 4.18ish which is far from 5.0 so many userscripts don't work, also I tested Violentmonkey similarly fails, so my only recommended solution is using a better browser
> 
> Tampermonkey beta v5.2.6198 works on opera gx

Ok I will test it out after my meal break, is that what you're using?

**Comment by ozilwg** [comment]
> > > @ozilwg after extensive research, I found Opera GX blocks latest Tampermonkey as malicious
> > > https://www.reddit.com/r/OperaGX/comments/19bvkbt/opera_gx_fullon_disabled_one_of_my_extensions/?rdt=61722 https://forums.opera.com/topic/30359/tampermonkey-chrome-extension-blocked/26?lang=en-US
> > > The last working version is 4.18ish which is far from 5.0 so many userscripts don't work, also I tested Violentmonkey similarly fails, so my only recommended solution is using a better browser
> > 
> > 
> > Tampermonkey beta v5.2.6198 works on opera gx
> 
> Ok I will test it out after my meal break, is that what you're using?

I am using Tampermonkey Beta installed from Chrome extensions. The extension doesn't show up on the right side in Google all the time. Script updates have been done.

![image](https://github.com/KudoAI/googlegpt/assets/94186149/ac7e5d21-9f3f-4e98-9621-153de03151fa)

**Comment by adamlui** [comment]
hey @ozilwg i got it to work

![Image](https://github.com/user-attachments/assets/f712a2e3-a7d1-4920-a43b-9a7c50e2a0ef)

(i still have to redesign the bg to match more) 

this is how I did it

in chrome://extensions, under Tampermonkey I checked this box

![Image](https://github.com/user-attachments/assets/c683d2dc-5045-4e5b-9d10-d9732df19251)

"Allow access to search page results"
