### ISSUE TITLE
string failed conversion

### ISSUE THREAD

**Issue by Vozf** [KudoAI/googlegpt#4]
Show a numbered list of queries related to this one:

[object Object]

**Comment by adamlui** [comment]
Hey @Vozf this only occurs in OpenAI mode, but if you turn on (the slower for now) Proxy mode...

![biX7lq2](https://github.com/KudoAI/googlegpt/assets/10906554/73502e1d-0be9-4760-94a4-3eabf12b22b2)

...it will work (often very slowly) but I have added this to my very long tasklist of many apps' tasks and thanks for reporting it!

**Comment by adamlui** [comment]
@Vozf I fixed it they show in OpenAI mode now
