### ISSUE TITLE
Disable (reply in en-us) postfix option

### ISSUE THREAD

**Issue by Vozf** [KudoAI/googlegpt#5]

**Comment by adamlui** [comment]
@Vozf is it because in OpenAI mode, it often just repeats your message back to you with this suffix? Because when that occurs, I looked at the logs, it said something wrong happened with OpenAI (so it could not generate a reply). So there is nothing wrong with including this suffix, but maybe when that specific error occurs, I can detail it to mask this from happening (but no such error ever occurs in Proxy mode)

**Comment by Vozf** [comment]
no, I mean to remove the postfix from the input message to chatgpt. I want to get replies in the language I've made the request

**Comment by adamlui** [comment]
@Vozf to the right of address bar, if you click userscript manager icon, scroll to Google got, underneath it click "Reply Language" then fill in your language, click OK then refresh Google

**Comment by Vozf** [comment]
Once again. I want to get the response in the language of the request. I don't want to fix a language. If I make a request in english I want a response in english. If I make a request in german I want to get a request in german. That's how chatgpt works. Currently despite request language I will get a response in one fixed language because of the added "reply in ...". There should be an option to disable this postfix at all

**Comment by adamlui** [comment]
I'm not gonna add this option just to accommodate your unusual use case when most users just want their native language but still type in English too, like this guy showed me once...

![xI9WkKV](https://github.com/KudoAI/googlegpt/assets/10906554/60dcc7a3-2f39-47eb-b365-bac9323a36c3)

...when you can just set the language to "the language of the query"

![image](https://github.com/KudoAI/googlegpt/assets/10906554/c20d4400-cd1b-49d8-bfde-c9fadf41f3ec)
![image](https://github.com/KudoAI/googlegpt/assets/10906554/db1ffe43-0e0f-4edc-baab-eb40f49f8d3d)
![image](https://github.com/KudoAI/googlegpt/assets/10906554/6c6eeb1e-45d0-41f8-9ddc-63f209262aa6)

**Comment by adamlui** [comment]
What I mean is this feature is a powerful bonus many find awesome, why would I disable it just for your rude demand, come on now just work around it

**Comment by adamlui** [comment]
@Vozf I just re-read your request and perhaps it wasn't as rude as initially assessed if that is how you naturally communicate, so I apologize for the labeling
